apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-server
  template:
    metadata:
      labels:
        app: random-server
    spec:
      containers:
      - name: random-server
        image: agrynov/step2:HW24
        ports:
        - containerPort: 8082
