apiVersion: apps/v1
kind: Deployment
metadata:
  name: danit-app
  namespace: default
  labels:
    app: danit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: danit-app
  template:
    metadata:
      labels:
        app: danit-app
    spec:
      containers:
      - name: danit-app
        image: agrynov/final:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
