- name: Install Jenkins and Nginx
  hosts: jenkins_master
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-17-jdk
          - gnupg
          - nginx
        state: present
        update_cache: yes

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Copy Nginx reverse proxy config
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/jenkins
        owner: root
        group: root
        mode: 0644

    - name: Enable Nginx config
      file:
        src: /etc/nginx/sites-available/jenkins
        dest: /etc/nginx/sites-enabled/jenkins
        state: link
        force: yes

    - name: Remove default Nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx
      systemd:
        name: nginx
        enabled: yes
        state: restarted
