# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы проекта в контейнер
COPY . .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем gunicorn
RUN pip install gunicorn

# Открываем порт 8000
EXPOSE 8000

# Запускаем приложение с помощью gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]