services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: students-app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app