global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: '7664674468:AAFe0v3oCVkU2OCidyIF66AUhI5dN38l-mE'
        chat_id: -1002858830803
        #parse_mode: Markdown
