apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: agrynov-app

commonLabels:
  app.kubernetes.io/name: agrynov-app
  app.kubernetes.io/part-of: step-final
