groups:
  - name: system_alerts
    rules:
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk space over 15"

      - alert: HighCPUUsage
        expr: (100 - avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High load CPU over 80"

      - alert: TargetDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Target unavailable"